### ISSUE TITLE
This language shares the same name with mine

### ISSUE THREAD

**Issue by chuangzaojun** [Karl-Lang/Karl#13]
This is my language 

[link](https://github.com/karl-dev-team/karl)

**Comment by pwaillette** [comment]
Hello ^^
It seems we have a tiny problem. You report that our languages have the same names, but mine is a few-days older, according to commits dates.
Please change your language, or don't ask me to change it, because I won't do it, sorry <3
![image](https://github.com/Karl-Lang/Karl/assets/46852063/a6b457a8-9674-48e1-802c-bdd5398b46b8)
![image](https://github.com/Karl-Lang/Karl/assets/46852063/fa786358-9228-40dc-97a6-90c34a75db4a)

**Comment by pwaillette** [comment]
If you want to discuss more about it, please contact me on discord: _alpaca.sama\_
